# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=46)),
                ('cityDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityInfoName', models.CharField(max_length=45)),
                ('cityInfoDesc', models.TextField()),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.City')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataName', models.CharField(max_length=45)),
                ('dataDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=30)),
                ('fName', models.CharField(max_length=45)),
                ('lName', models.CharField(max_length=45)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=45)),
                ('contactNumber', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=45)),
                ('typeDesc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserType'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='userTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserType'),
        ),
        migrations.AddField(
            model_name='cityinfo',
            name='userTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserType'),
        ),
    ]
