# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
