# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170830_1200'),
        ('login', '0003_auto_20170830_1212'),
    ]

    operations = [
    ]
