# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contactNumber',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default='2016-01-01'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
