# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170911_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, default='2016-01-01', null=True),
        ),
    ]
