# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171003_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='businessmanInfo',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='studentInfo',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='touristInfo',
            field=models.URLField(default=''),
        ),
    ]
