# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171020_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
